Support cli arguments to nvim.

diff --git a/nvim b/nvim
--- a/nvim
+++ b/nvim
@@ -1,4 +1,30 @@
 #!/bin/sh
+function usage
+{
+	echo "Usage: nvim [directory]"
+	echo ""
+	echo "Where directory is where you want to store your notes."
+	echo ""
+	echo "Environment variables:"
+	echo "NVIM_HOME: Which directory to use as a default (if not overridden via command line). Defaults to current directory."
+	echo "NVIM_EDITOR: Command to execute to invoke vim. Defaults to 'vim'"
+	exit 1
+}
+
+if [[ "$#" -gt 1 ]]
+then
+	usage
+fi
+
+if [[ "$#" -gt 0 ]]
+then
+	if [[ "$1" == "-h" || "$1" == "--help" ]]
+	then
+		usage
+	fi
+	export NVIM_HOME=$1
+fi
+
 if [[ -z "$NVIM_HOME" ]]
 then
   export NVIM_HOME=$PWD
@@ -7,6 +33,12 @@ fi
 if [[ -z "$NVIM_EDITOR" ]]
 then
   export NVIM_EDITOR='vim'
+fi
+
+if [[ ! -d "$NVIM_HOME" ]]
+then
+	echo "Error: directory $NVIM_HOME does not appear to exist."
+	exit 1
 fi
 
 cd "$NVIM_HOME" && $NVIM_EDITOR -c 'exec NVIM_init()'
